---
output:
  pdf_document: default
  html_document: default
---

# Experiment 13

**Name:** Jaswinderpal Singh\
**Class:** M.Sc. Statistics, Sem 1 \
**Date:** December 10, 2021

```{r}
# To Create a CSV file in Excel with name ‘temp’ and import this into R
data = read.csv("temp.csv")
attach(data)
```

## **1. Aim:** To Generate tables and apply chisq tests

```{r}
# (i) 2x2 table for sex and locality. 
tab1 = table(sex, locality)
rownames(tab1) = c("Male","Female")
colnames(tab1) = c("Rural","Urban")
tab1
# Test whether sex distribution is independent of locality
# H_0: Sex distribution is independent of locality.
# H_1: Sex distribution is not independent of locality.
cqt = chisq.test(tab1)
cqt$expected
summary(tab1)
```
$H_0$ is accepted.
```{r}
#











#
```

```{r warning=FALSE}
# (ii) Is there any significant association between mutation and religion?
#H_0: There is no significant association between mutation and religion.
#H_1: There is a significant association between mutation and religion.
tab2 = table(mutation, religion)
rownames(tab2) = c("Not Mutated", "Mutated")
colnames(tab2) = c("Hindu","Muslim","Sikh","Christian")
tab2
cq = chisq.test(tab2)
cq$expected
cq
```
$H_0$ is accepted.
```{r}
#













#
```

```{r,warning=FALSE}
# (iii) To Test that for age, the population variance is different from 5 i.e        



# Also find 95% Confidence Intervals for 
(n = length(age))
(s2 = var(age))
csq = (n-1)*s2/5
csq  # Calculated Value of Chi Square
df = n-1
df # degrees of freedom

# Critical Values
(tab_alp_by2 = qchisq(0.05/2,df))
(tab_1mnsalp_by2 = qchisq(0.05/2,df,lower.tail = F))
# H_0 is rejected.
# 95% confidence intervals
c((n-1)*s2/tab_1mnsalp_by2, (n-1)*s2/tab_alp_by2)

```

```{r}
#














#
```

\newpage

## **2. Aim:** To find Chisq pdf values and densities and plot graphs

```{r}
# (i) Probably density function of Chi-square distribution at

# (a): f(0), with df=5
dchisq(0, 5)  

# (b): f(5), with df=10
dchisq(5, 10)  

# (c) Generate a sequence x<- seq(0,20,by=.1) and also y<- dchisq(x) with df=5, for Chi-square and then plot (x,y). Draw the curve on plot (x,y).
x = seq(0, 20, by = 0.1)
y = dchisq(x, 5)
x
y
plot(x,y,pch = 20, col="blue4")
curve(dchisq(x,5), 0, 20, lwd = 2, col="red", add = TRUE)



# (ii) Cumulative distribution function of Chi-square distribution at

# (a): cdf F(3), with df=4
pchisq(3,4)

# (b): cdf F(0) with df=6
pchisq(0,6)

# (c): F(X>3), with df=4
pchisq(3,4,lower.tail = F)



# (iii) Inverse cumulative distribution function of Chi-square distribution at

# (a): F^-1 (0), with df=3
qchisq(0, 3)

# (b): F^-1 (0.6), with df=5
qchisq(0.6, 5)

# (c): To Generate a sequence x<- seq(0,.9 by=.01) and also y<- qchisq(x) with df=8, then plot (x,y).
X = seq(0, 0.9, by = 0.01)
Y = qchisq(X, 8)
X
Y
plot(X,Y,pch=20, col="green3")



# (iv) Generate a random sample of 10 observations from a Chi-square distribution with df=10.
rchisq(10, 10)

```
